.TH ISTAR\-CLI 8 2023-02-27

.SH NAME
istar\-cli \- install istar on disk image

.SH SYNOPSIS
\fistar-cli\fR <\fIdisk image\fR>

.SH DESCRIPTION

.SH EXIT STATUS
Exit with status 0 if success. 1 if fail.

.SH BUGS
See <https://github.com/d0p1s4m4/Istar/issues> for issues.

.SH COPYRIGHT
Copyright \(co 2023 d0p1.
.br
License BSD 3 Clause: <https://opensource.org/license/bsd-3-clause/>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
.BR istar\&.lisp (5)
